language: java
jdk: oraclejdk8

script: make build

deploy:
  provider: script
  script: make deploy
  on:
    tags: true

before_deploy: openssl aes-256-cbc -K $encrypted_bbcf2f683b6c_key -iv $encrypted_bbcf2f683b6c_iv -in private-key.gpg.enc -out private-key.gpg -d

after_deploy: rm .deploy/private-key.gpg
